"use client"
import { Roboto } from "next/font/google";
import "./globals.css";

import Navbar from "@/components/Navbar/Navbar";
import Footer from "@/components/Footer/Footer";


const roboto = Roboto({
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "700", "900"],
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${roboto.className} bg-gray-100 font-secondary text-[20px] text-secondary`}
      >
        {/* NAVBAR */}
        <Navbar />
        {/* == NAVBAR == */}

        {/* MAIN CONTENT */}
        <main className="max-w-[1920px] mx-auto bg-white overflow-hidden">

          {children}

        </main>
        {/* == MAIN CONTENT == */}

        {/* FOOTER */}
        <Footer />
        {/* == FOOTER == */}
      </body>
    </html>
  );
}
